# FinPulse — Bank Transaction & Financial Analytics

### Python Exploratory Data Analysis

This notebook analyzes bank transaction data to understand:

- Transaction activity
- Deposit and withdrawal behavior
- Cash flow patterns
- Account balance trends
- High-value transactions
- Transaction descriptions
- Financial outliers

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path

In [2]:
PROJECT_ROOT = Path(r"C:\FinPulse")

DATA_PATH = PROJECT_ROOT / "data" / "process" / "new one.csv"

CHART_PATH = PROJECT_ROOT / "python" / "charts"

CHART_PATH.mkdir(
    parents=True,
    exist_ok=True
)

print("Project Root:", PROJECT_ROOT)
print("Dataset Path:", DATA_PATH)
print("Chart Path:", CHART_PATH)

Project Root: C:\FinPulse
Dataset Path: C:\FinPulse\data\process\new one.csv
Chart Path: C:\FinPulse\python\charts

In [3]:
if DATA_PATH.exists():
    print("Dataset found successfully.")
else:
    print("Dataset not found.")

Dataset found successfully.

In [5]:
df = pd.read_csv(DATA_PATH)

In [6]:
df.head()

,Account No,DATE,TRANSACTION DETAILS,CHQ.NO.,VALUE DATE,WITHDRAWAL AMT,DEPOSIT AMT,BALANCE AMT
0,4.090006e+11,2017-06-29,TRF FROM Indiaforensic SERVICES,NaN,2017-06-29,0,1000000,1000000.0
1,4.090006e+11,2017-07-05,TRF FROM Indiaforensic SERVICES,NaN,2017-07-05,0,1000000,2000000.0
2,4.090006e+11,2017-07-18,FDRL/INTERNAL FUND TRANSFE,NaN,2017-07-18,0,500000,2500000.0
3,4.090006e+11,2017-08-01,TRF FRM Indiaforensic SERVICES,NaN,2017-08-01,0,3000000,5500000.0
4,4.090006e+11,2017-08-16,FDRL/INTERNAL FUND TRANSFE,NaN,2017-08-16,0,500000,6000000.0

In [7]:
df.head()

,Account No,DATE,TRANSACTION DETAILS,CHQ.NO.,VALUE DATE,WITHDRAWAL AMT,DEPOSIT AMT,BALANCE AMT
0,4.090006e+11,2017-06-29,TRF FROM Indiaforensic SERVICES,NaN,2017-06-29,0,1000000,1000000.0
1,4.090006e+11,2017-07-05,TRF FROM Indiaforensic SERVICES,NaN,2017-07-05,0,1000000,2000000.0
2,4.090006e+11,2017-07-18,FDRL/INTERNAL FUND TRANSFE,NaN,2017-07-18,0,500000,2500000.0
3,4.090006e+11,2017-08-01,TRF FRM Indiaforensic SERVICES,NaN,2017-08-01,0,3000000,5500000.0
4,4.090006e+11,2017-08-16,FDRL/INTERNAL FUND TRANSFE,NaN,2017-08-16,0,500000,6000000.0

In [8]:
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

Number of Rows: 116202
Number of Columns: 8

In [9]:
df.columns.tolist()

['Account No',
 'DATE',
 'TRANSACTION DETAILS',
 'CHQ.NO.',
 'VALUE DATE',
 'WITHDRAWAL AMT',
 'DEPOSIT AMT',
 'BALANCE AMT']

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116202 entries, 0 to 116201
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Account No           116201 non-null  float64
 1   DATE                 116201 non-null  object
 2   TRANSACTION DETAILS  113702 non-null  object
 3   CHQ.NO.              905 non-null     float64
 4   VALUE DATE           116201 non-null  object
 5   WITHDRAWAL AMT       116202 non-null  int64
 6   DEPOSIT AMT          116202 non-null  int64
 7   BALANCE AMT          116201 non-null  float64
dtypes: float64(3), int64(2), object(3)
memory usage: 7.1+ MB

In [11]:
df.describe(include="all")

,Account No,DATE,TRANSACTION DETAILS,CHQ.NO.,VALUE DATE,WITHDRAWAL AMT,DEPOSIT AMT,BALANCE AMT
count,1.162010e+05,116201,113702,905.000000,116201,1.162020e+05,1.162020e+05,1.162010e+05
unique,NaN,1294,43213,NaN,1294,NaN,NaN,NaN
top,NaN,2017-07-27,FDRL/INTERNAL FUND TRANSFE,NaN,2017-07-27,NaN,NaN,NaN
freq,NaN,567,8839,NaN,567,NaN,NaN,NaN
mean,2.002261e+11,NaN,NaN,791614.503867,NaN,2.068739e+06,2.052376e+06,-1.404852e+09
std,2.044558e+11,NaN,NaN,151205.932910,NaN,7.696851e+06,6.652138e+06,5.348202e+08
min,1.196428e+06,NaN,NaN,1.000000,NaN,0.000000e+00,0.000000e+00,-2.045201e+09
25%,1.196428e+06,NaN,NaN,704231.000000,NaN,0.000000e+00,0.000000e+00,-1.690383e+09
50%,1.196711e+06,NaN,NaN,873812.000000,NaN,0.000000e+00,5.000000e+03,-1.661395e+09
75%,4.090004e+11,NaN,NaN,874167.000000,NaN,2.682500e+04,5.000000e+05,-1.236888e+09
max,4.090006e+11,NaN,NaN,874525.000000,NaN,4.594475e+08,5.448000e+08,8.500000e+06

In [12]:
missing_summary = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing Percentage": df.isnull().mean() * 100
})

missing_summary.sort_values(
    "Missing Count",
    ascending=False
)

                     Missing Count  Missing Percentage
CHQ.NO.                     115297           99.221184
TRANSACTION DETAILS           2500            2.151426
Account No                       1            0.000861
DATE                             1            0.000861
VALUE DATE                       1            0.000861
BALANCE AMT                      1            0.000861
WITHDRAWAL AMT                   0            0.000000
DEPOSIT AMT                      0            0.000000

In [19]:
duplicate_count = df.duplicated().sum()

print("Duplicate Rows:", duplicate_count)

Duplicate Rows: 0

In [20]:
df = df.drop_duplicates().reset_index(drop=True)

In [21]:
print("Rows after removing duplicates:", len(df))
print("Remaining duplicates:", df.duplicated().sum())

Rows after removing duplicates: 116153
Remaining duplicates: 0

In [23]:
df["DATE"] = pd.to_datetime(
    df["DATE"],
    errors="coerce"
)

df["VALUE DATE"] = pd.to_datetime(
    df["VALUE DATE"],
    errors="coerce"
)

In [24]:
amount_columns = [
    "WITHDRAWAL AMT",
    "DEPOSIT AMT",
    "BALANCE AMT"
]

In [25]:
for column in amount_columns:
    df[column] = pd.to_numeric(
        df[column],
        errors="coerce"
    )

In [26]:
df[amount_columns].dtypes

WITHDRAWAL AMT      int64
DEPOSIT AMT         int64
BALANCE AMT       float64
dtype: object

In [27]:
df["WITHDRAWAL AMT"] = (
    df["WITHDRAWAL AMT"].fillna(0)
)

df["DEPOSIT AMT"] = (
    df["DEPOSIT AMT"].fillna(0)
)

In [28]:
df.isnull().sum()

Account No                  1
DATE                        1
TRANSACTION DETAILS      2500
CHQ.NO.                115248
VALUE DATE                  1
WITHDRAWAL AMT              0
DEPOSIT AMT                 0
BALANCE AMT                 1
dtype: int64

In [29]:
print("First Transaction Date:")
print(df["DATE"].min())

print("\nLast Transaction Date:")
print(df["DATE"].max())

First Transaction Date:
2015-01-01 00:00:00

Last Transaction Date:
2019-03-05 00:00:00

In [31]:
unique_accounts = df["Account No"].nunique()

print("Unique Accounts:", unique_accounts)

Unique Accounts: 10

In [32]:
df["TRANSACTION TYPE"] = np.select(
    [
        df["DEPOSIT AMT"] > 0,
        df["WITHDRAWAL AMT"] > 0
    ],
    [
        "Deposit",
        "Withdrawal"
    ],
    default="Other"
)

In [33]:
df["TRANSACTION TYPE"].value_counts()

TRANSACTION TYPE
Deposit       62467
Withdrawal    41572
Other         12114
Name: count, dtype: int64

In [34]:
df["NET AMOUNT"] = (
    df["DEPOSIT AMT"]
    - df["WITHDRAWAL AMT"]
)

In [37]:
df[
    [
        "DEPOSIT AMT",
        "WITHDRAWAL AMT",
        "NET AMOUNT"
    ]
].tail()

        DEPOSIT AMT  WITHDRAWAL AMT  NET AMOUNT
116148       300000          117934      182066
116149       300000               0      300000
116150            0               0           0
116151            0          109869     -109869
116152            0            5000       -5000

In [38]:
df["YEAR"] = df["DATE"].dt.year

df["MONTH"] = df["DATE"].dt.month

df["MONTH NAME"] = df["DATE"].dt.month_name()

df["DAY"] = df["DATE"].dt.day

df["DAY NAME"] = df["DATE"].dt.day_name()

df["WEEKDAY"] = df["DATE"].dt.dayofweek

In [39]:
df.head()

,Account No,DATE,TRANSACTION DETAILS,CHQ.NO.,VALUE DATE,WITHDRAWAL AMT,DEPOSIT AMT,BALANCE AMT,TRANSACTION TYPE,NET AMOUNT,YEAR,MONTH,MONTH NAME,DAY,DAY NAME,WEEKDAY
0,4.090006e+11,2017-06-29,TRF FROM Indiaforensic SERVICES,NaN,2017-06-29,0,1000000,1000000.0,Deposit,1000000,2017.0,6.0,June,29.0,Thursday,3.0
1,4.090006e+11,2017-07-05,TRF FROM Indiaforensic SERVICES,NaN,2017-07-05,0,1000000,2000000.0,Deposit,1000000,2017.0,7.0,July,5.0,Wednesday,2.0
2,4.090006e+11,2017-07-18,FDRL/INTERNAL FUND TRANSFE,NaN,2017-07-18,0,500000,2500000.0,Deposit,500000,2017.0,7.0,July,18.0,Tuesday,1.0
3,4.090006e+11,2017-08-01,TRF FRM Indiaforensic SERVICES,NaN,2017-08-01,0,3000000,5500000.0,Deposit,3000000,2017.0,8.0,August,1.0,Tuesday,1.0
4,4.090006e+11,2017-08-16,FDRL/INTERNAL FUND TRANSFE,NaN,2017-08-16,0,500000,6000000.0,Deposit,500000,2017.0,8.0,August,16.0,Wednesday,2.0

In [40]:
total_transactions = len(df)

total_deposits = df["DEPOSIT AMT"].sum()

total_withdrawals = df["WITHDRAWAL AMT"].sum()

net_cash_flow = df["NET AMOUNT"].sum()

average_transaction = (
    df["NET AMOUNT"].abs().mean()
)